version: '3.8'

networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.69.0.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
      - WEBUI_PORT=8888
      - TORRENTING_PORT=6881
    volumes:
      - /path/to/your/folder/qbittorrent/config:/config
      - /path/to/your/folder/qbittorrent/completed:/downloads/completed
      - /path/to/your/folder/qbittorrent/completed:/downloads/incomplete
      - /path/to/your/folder/qbittorrent/completed:/downloads/torrents
      - /path/to/your/folder/plex/tv_shows:/plex_tv
    ports:
      - 8888:8888
      - 6881:6881
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.6

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/folder/sonarr:/config
      - /path/to/your/folder/data:/data
      - /path/to/your/folder/downloads:/downloads
      - /path/to/your/folder/qbittorrent/completed:/completed
      - /path/to/your/folder/qbittorrent/completed:/downloads/completed
    ports:
      - 8989:8989
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.3

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/folder/radarr:/config
      - /path/to/your/folder/data:/data
      - /path/to/your/folder/downloads:/downloads
      - /path/to/your/folder/qbittorrent/completed:/completed
      - /path/to/your/folder/qbittorrent/completed:/downloads/completed
    ports:
      - 7878:7878
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.5

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
    volumes:
      - /path/to/your/folder/lidarr:/config
      - /path/to/your/folder/downloads:/downloads
    ports:
      - 8686:8686
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.2

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
    volumes:
      - /path/to/your/folder/bazarr:/config
      - /path/to/your/folder/downloads:/downloads
    ports:
      - 6767:6767
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.4

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kampala
    volumes:
      - /path/to/your/folder/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      servarrnetwork:
        ipv4_address: 172.69.0.7

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=Africa/Kampala
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
