version: '3.8'

networks:
  servarrnetwork:
    name: servarrnetwork
    ipam:
      config:
        - subnet: 172.69.0.0/24

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      - deunhealth.restart.on.unhealthy=true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - /path/to/your/media-server/qbittorrent:/config
      - /path/to/your/media-server/qbittorrent/completed:/downloads/completed
      - /path/to/your/media-server/qbittorrent/completed:/downloads/incomplete
      - /path/to/your/media-server/qbittorrent/completed:/downloads/torrents
      - /path/to/your/media-server/media/tv shows:/plex_tv
    ports:
      - "${WEBUI_PORT}:8888"
      - "${TORRENTING_PORT}:6881"
    networks:
      - servarrnetwork

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/media-server/sonarr:/config
      - /path/to/your/media-server/downloads:/downloads
      - /path/to/your/media-server/qbittorrent/completed:/completed
      - /path/to/your/media-server/qbittorrent/completed:/downloads/completed
    ports:
      - 8989:8989
    networks:
      - servarrnetwork

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /path/to/your/media-server/radarr:/config
      - /path/to/your/media-server/downloads:/downloads
      - /path/to/your/media-server/qbittorrent/completed:/completed
      - /path/to/your/media-server/qbittorrent/completed:/downloads/completed
    ports:
      - 7878:7878
    networks:
      - servarrnetwork

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /path/to/your/media-server/lidarr:/config
      - /path/to/your/media-server/downloads:/downloads
      - /path/to/your/media-server/media/music:/music
    ports:
      - 8686:8686
    networks:
      - servarrnetwork

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /path/to/your/media-server/bazarr:/config
      - /path/to/your/media-server/downloads:/downloads
    ports:
      - 6767:6767
    networks:
      - servarrnetwork

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /path/to/your/media-server/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - servarrnetwork

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: "none"
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
